spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/db_learn
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: project-for-learn
      connection-timeout: 20000
      minimum-idle: ${HIKARI_POOL_SIZE:10}
      max-lifetime: 120000
  jpa:
    hibernate:
      ddl-auto: update
  activemq:
    pool:
      max-connections: 10
server:
  port: 8020